[project]
name = "acp-projs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "acp-sdk>=1.0.0",
    "duckduckgo-search>=8.1.1",
    "load-dotenv>=0.1.0",
    "nest-asyncio>=1.6.0",
    "smolagents[litellm]>=1.20.0",
]
